# Generated by Django 2.2.5 on 2019-09-30 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0002_auto_20190930_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100, verbose_name='property name')),
                ('property_description', models.CharField(max_length=2000, verbose_name='property description')),
                ('property_available', models.BooleanField(default=True)),
                ('property_rent', models.FloatField(max_length=100)),
                ('property_address', models.CharField(max_length=500)),
                ('property_location', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('property_holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='property holder')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_img', models.FileField(upload_to='images/property')),
                ('property_img_tag', models.CharField(max_length=500)),
                ('prop_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eshopper.Property')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
