# Generated by Django 2.2.5 on 2019-10-04 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0003_property_propertyimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_location',
            new_name='property_landmark',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_holder',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='property holder'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='prop_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='eshopper.Property'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property_img',
            field=models.ImageField(upload_to='images/property'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property_img_tag',
            field=models.CharField(default='Property Image', max_length=500),
        ),
    ]
