# Generated by Django 2.2.5 on 2019-10-15 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0005_auto_20191004_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='prop_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eshopper.Property'),
        ),
    ]
